name: Package and Release Firefox Extension

on: 
  push:
    branches:
      - main  # Adjust this as per your main branch
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git User
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Set your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Lint with ESLint
      run: npx eslint .

    - name: Get Version
      id: get_version
      run: echo "VERSION=$(jq -r .version src/manifest.json)" >> $GITHUB_ENV

    - name: Package Extension
      run: |
        cd src
        zip -r -Z deflate ../ImageConverter-${{ env.VERSION }}.zip manifest.json background.js content-script.js _locales/ icons/icon-48.png icons/icon-96.png

    - name: Create and Upload Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "v${{ env.VERSION }}"
        prerelease: false
        title: "Release v${{ env.VERSION }}"
        files: |
          ImageConverter-${{ env.VERSION }}.zip
